- id: arm_blink_when_away
  alias: "Arm Blink When Away"
  trigger:
    platform: state
    entity_id: person.jack
    to: "not_home"
  action:
    service: alarm_control_panel.alarm_arm_away
    target:
      entity_id: alarm_control_panel.blink_camera_1

- id: disarm_blink_when_present
  alias: "Disarm Blink When Home"
  trigger:
    platform: state
    entity_id: person.jack
    to: "home"
  action:
    service: alarm_control_panel.alarm_disarm
    target:
      entity_id: alarm_control_panel.blink_camera_1

- id: e6d88513c8e44aaf959d79f90b0244211
  alias: Turn on desk light when office door is open
  initial_state: "on"
  trigger:
    platform: state
    entity_id: binary_sensor.office_door
    to: "on"
  action:
    service: light.turn_on
    entity_id: light.desk

- id: e6d88513c8e44aaf959d79f90b0bf12
  alias: Turn off desk light when office door is closed
  initial_state: "on"
  trigger:
    platform: state
    entity_id: binary_sensor.office_door
    to: "off"
  action:
    service: light.turn_off
    entity_id: light.desk

- id: e6d88513c8e44aaf959d79f90b0bf211
  alias: Turn bedroom lights on when motion detected
  trigger:
    platform: state
    entity_id: binary_sensor.bedroom_sensor
    to: "on"
  condition:
    - condition: state
      entity_id: group.main_lights
      state: "off"
    - condition: time
      after: "08:30"
      before: "21:00"
  action:
    - entity_id: group.main_lights
      service: light.turn_on
    - entity_id: group.light_strips
      service: light.turn_on

- id: e6djklc8e44aaf959d79f90b0bf211
  alias: Turn off bedroom light when Jack is not home
  trigger:
    platform: state
    entity_id: binary_sensor.bedroom_sensor
    to: "off"
    for:
      minutes: 15
  action:
    - entity_id: group.main_lights
      service: light.turn_off
    - entity_id: group.light_strips
      service: light.turn_off

- id: e6d88513c8esdk90b0bf211
  alias: "Work Calendar"
  trigger:
    platform: state
    entity_id: sensor.time_to_work_event
    to: "5"
  condition:
    - condition: state
      entity_id: "person.jack"
      state: "home"
  action:
    - service: light.turn_on
      entity_id: group.light_strips
      data:
        brightness: 180
        rgb_color: [255, 0, 0]
    - service: script.flash_lights
    - service: notify.alexa_media_jack_s_echo_dot
      data:
        message: Hi Jack, {{ state_attr('calendar.jack_nelson_tails_com', 'message') }} is starting shortly.
        data:
          type: announce
    - service: light.turn_on
      entity_id: group.light_strips
      data:
        brightness: 180
        rgb_color: [254, 207, 255]

- id: e6d88513c8esdk9sdf
  alias: "Personal Calendar"
  trigger:
    platform: state
    entity_id: sensor.time_to_personal_event
    to: "5"
  condition:
    - condition: state
      entity_id: "person.jack"
      state: "home"
  action:
    - service: light.turn_on
      entity_id: group.light_strips
      data:
        brightness: 180
        rgb_color: [0, 255, 0]
    - service: script.flash_lights
    - service: notify.alexa_media_jack_s_echo_dot
      data:
        message: Hi Jack, {{ state_attr('calendar.jack_nelson_personal', 'message') }} is starting shortly.
        data:
          type: announce
    - service: light.turn_on
      entity_id: group.light_strips
      data:
        brightness: 180
        rgb_color: [254, 207, 255]
