- alias: Turn on desk ligtht when there is movement
  initial_state: "on"
  trigger:
    platform: state
    entity_id: binary_sensor.desk_sensor
    to: "on"
  action:
    service: light.turn_on
    entity_id: light.desk

- alias: Turn off desk light 10 minutes after last movement
  initial_state: "on"
  trigger:
    platform: state
    entity_id: binary_sensor.desk_sensor
    to: "off"
    for:
      seconds: 300
  action:
    service: light.turn_off
    entity_id: light.desk

- id: e6d88513c8e44aaf959d79f90b0bf211
  alias: Turn bedroom lights on when Jack is home
  trigger:
  condition:
    - condition: state
      entity_id: sun.sun
      state: below_horizon
    - condition: numeric_state
      entity_id: sun.sun
      value_template: "{{ state.attributes.elevation }}"
      below: 2.0
    - condition: state
      entity_id: light.sofa
      state: "off"
  action:
    - entity_id: light.sofa
      service: light.turn_on
