- alias: Turn on desk light when office door is open
  initial_state: "on"
  trigger:
    platform: state
    entity_id: binary_sensor.office_door
    to: "on"
  action:
    service: light.turn_on
    entity_id: light.desk

- alias: Turn off desk light when office door is closed
  initial_state: "on"
  trigger:
    platform: state
    entity_id: binary_sensor.office_door
    to: "off"
  action:
    service: light.turn_off
    entity_id: light.desk

- id: e6d88513c8e44aaf959d79f90b0bf211
  alias: Turn bedroom lights on when motion detected
  trigger:
    platform: state
    entity_id: binary_sensor.bedroom_sensor
    to: "on"
  condition:
    - condition: state
      entity_id: group.main_lights
      state: "off"
    - condition: time
      after: "08:30"
      before: "20:00"
  action:
    - entity_id: group.main_lights
      service: light.turn_on
    - entity_id: group.light_strips
      service: light.turn_on

- alias: Turn off bedroom light when Jack is not home
  trigger:
    platform: state
    entity_id: binary_sensor.bedroom_sensor
    to: "off"
    for:
      minutes: 15
  action:
    - entity_id: group.main_lights
      service: light.turn_off
    - entity_id: group.light_strips
      service: light.turn_off
