- id: e6d88513c8e44aaf959d79f90b0244211
  alias: Turn on desk light when office door is open
  initial_state: "on"
  trigger:
    platform: state
    entity_id: binary_sensor.office_door
    to: "on"
  action:
    service: light.turn_on
    entity_id: light.desk

- id: e6d88513c8e44aaf959d79f90b0bf12
  alias: Turn off desk light when office door is closed
  initial_state: "on"
  trigger:
    platform: state
    entity_id: binary_sensor.office_door
    to: "off"
  action:
    service: light.turn_off
    entity_id: light.desk

- id: e6d88513c8e44aaf959d79f90b0bf211
  alias: Turn bedroom lights on when motion detected
  trigger:
    platform: state
    entity_id: binary_sensor.bedroom_sensor
    to: "on"
  condition:
    - condition: state
      entity_id: group.main_lights
      state: "off"
    - condition: time
      after: "08:30"
      before: "20:00"
  action:
    - entity_id: group.main_lights
      service: light.turn_on
    - entity_id: group.light_strips
      service: light.turn_on

- id: e6djklc8e44aaf959d79f90b0bf211
  alias: Turn off bedroom light when Jack is not home
  trigger:
    platform: state
    entity_id: binary_sensor.bedroom_sensor
    to: "off"
    for:
      minutes: 15
  action:
    - entity_id: group.main_lights
      service: light.turn_off
    - entity_id: group.light_strips
      service: light.turn_off

- id: e6d88513c8esdk90b0bf211
  alias: "Tails Meetings"
  trigger:
    platform: state
    entity_id: calendar.jack_nelson_tails_com
    to: "on"
  action:
    - service: light.turn_on
      entity_id: group.light_strips
      data:
        brightness: 200
        rgb_color: [255, 0, 0]

- id: e6d88513c8esdk9
  alias: "Personal Calendar"
  trigger:
    platform: state
    entity_id: sensor.timetoevent
    to: "5"
  action:
    - service: script.flash_lights
    - service: notify.alexa_media_jack_s_echo_dot
      data:
        message: Hi, {{ state_attr('calendar.jack_nelson_personal', 'message') }} is starting shortly.
        data:
          type: announce
    - service: light.turn_on
      entity_id: group.light_strips
      data:
        brightness: 200
        rgb_color: [0, 255, 0]
        flash: short
