- alias: Turn on desk ligtht when there is movement
  initial_state: "on"
  trigger:
    platform: state
    entity_id: binary_sensor.desk_sensor
    to: "on"
  action:
    service: light.turn_on
    entity_id: light.desk

- alias: Turn off desk light 10 minutes after last movement
  initial_state: "on"
  trigger:
    platform: state
    entity_id: binary_sensor.desk_sensor
    to: "off"
    for:
      seconds: 600
  action:
    service: light.turn_off
    entity_id: light.desk
