- alias: Turn on desk light when office door is open
  initial_state: "on"
  trigger:
    platform: state
    entity_id: binary_sensor.office_door
    to: "on"
  action:
    service: light.turn_on
    entity_id: light.desk

- alias: Turn off desk light when office door is closed
  initial_state: "on"
  trigger:
    platform: state
    entity_id: binary_sensor.office_door
    to: "off"
  action:
    service: light.turn_off
    entity_id: light.desk

- id: e6d88513c8e44aaf959d79f90b0bf211
  alias: Turn bedroom lights on when Jack is home
  trigger:
    platform: state
    entity_id: binary_sensor.bedroom_sensor
    to: "on"
  condition:
    - condition: state
      entity_id: light.sofa
      state: "off"
  action:
    - entity_id: light.sofa
      service: light.turn_on
