- alias: Turn on desk ligtht when there is movement
  initial_state: "on"
  trigger:
    platform: state
    entity_id: binary_sensor.desk_sensor
    to: "on"
  action:
    service: light.turn_on
    entity_id: light.desk

- alias: Turn off desk light 10 minutes after last movement
  initial_state: "on"
  trigger:
    platform: state
    entity_id: binary_sensor.desk_sensor
    to: "off"
    for:
      seconds: 300
  action:
    service: light.turn_off
    entity_id: light.desk

- alias: "Turn bedroom lights on when Jack is home"
  trigger:
    platform: sun
    event: sunset
    offset: "-00:45:00"
  condition:
    - condition: or
      conditions:
        - before: sunrise
          condition: sun
        - after: sunset
          condition: sun
    - condition: state
      entity_id: person.jack
      state: home
  action:
    service: light.turn_on
    target:
      entity_id: light.sofa, light.bed
