####################################################
#                                                  #
#                Default Config                    #
#                                                  #
####################################################
# https://www.home-assistant.io/integrations/default_config/
# Configure a default setup of Home Assistant (frontend, api, etc)
#default_config:
person:
updater:
zone:
zeroconf:
system_health:
sun:
ssdp:
map:
logbook:
config:
history:
mobile_app:
api:
logger:
  default: info
  logs:
    homeassistant.components.rest_command: debug
http:
  base_url: https://jacknelson.info

####################################################
#                                                  #
#                   CUSTOMIZING                    #
#                                                  #
####################################################
# https://www.home-assistant.io/docs/configuration/customizing-devices/
# https://home-assistant.io/docs/configuration/basic/
homeassistant:
  external_url: "https://jacknelson.info"
  internal_url: "http://192.168.1.154:8123"
  latitude: 51.4665
  longitude: -0.1416
  unit_system: metric
  elevation: 9
  auth_providers:
    - type: homeassistant
    - type: trusted_networks
      trusted_networks:
        - 127.0.0.1
        - 172.0.0.0/8
        - ::1
        - fd00::/8
  time_zone: Europe/London
  whitelist_external_dirs:
    - /config
  allowlist_external_dirs:
    - /tmp
    - /camera_vids

# Text to speech
tts:
  - platform: google_translate

alexa:
  smart_home:

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

frontend:
  themes: !include_dir_merge_named themes

####################################################
#                                                  #
#                       MQTT                       #
#                                                  #
####################################################
mqtt:
  discovery: true
  broker: 192.168.1.154:1883
  birth_message:
    topic: "homeassistant/status"
    payload: "online"
  will_message:
    topic: "homeassistant/status"
    payload: "offline"

####################################################
#                                                  #
#                    COFFEE                        #
#                                                  #
####################################################
sensor:
  - platform: rest
    resource: http://192.168.1.154:2080/api/192.168.1.126/status
    name: smarter_coffee_status
    scan_interval: 20
    value_template: "{{ value_json.status.ready }}"

  - platform: rest
    resource: http://192.168.1.154:2080/api/192.168.1.126/status
    name: smarter_coffee_enoughwater
    scan_interval: 20
    value_template: "{{ value_json.status.enoughwater }}"

  - platform: rest
    resource: http://192.168.1.154:2080/api/192.168.1.126/status
    name: smarter_coffee_carafe
    scan_interval: 20
    value_template: "{{ value_json.status.carafe }}"

  - platform: fitbit
    clock_format: 24H
    monitored_resources:
      - "body/weight"
      - "activities/calories"
      - "activities/steps"
      - "sleep/minutesAsleep"
      - "body/bmi"

  - platform: time_date
    display_options:
      - "time"

  - platform: template
    sensors:
      time_to_personal_event:
        friendly_name: Time to Next Personal Event
        value_template: >-
          {% if states.calendar.jack_nelson_personal.attributes.start_time %}
            {{((as_timestamp(states.calendar.jack_nelson_personal.attributes.start_time) - as_timestamp(now())) / 60) | default(10) | int }}
          {%- else -%}
            0
          {%- endif %}
      time_to_work_event:
        friendly_name: Time to Next Work Event
        value_template: >-
          {% if states.calendar.jack_nelson_tails_com.attributes.start_time %}
            {{((as_timestamp(states.calendar.jack_nelson_tails_com.attributes.start_time) - as_timestamp(now())) / 60) | default(10) | int }}
          {%- else -%}
            0
          {%- endif %}

rest_command:
  make_coffee:
    url: "http://192.168.1.154:2080/api/192.168.1.126/start"
    method: get
####################################################
#                                                  #
#                    GOOGLE                        #
#                                                  #
####################################################
google:
  client_id: !secret google_client_id
  client_secret: !secret google_client_secret

####################################################
#                                                  #
#                    ALEXA                         #
#                                                  #
####################################################
alexa_media:
  accounts:
    - email: !secret amazon_user
      password: !secret amazon_password
      url: amazon.co.uk
      include_devices:
        - "Jack's Echo Dot"

####################################################
#                                                  #
#                   OCTOPRINT                      #
#                                                  #
####################################################
camera:
  - platform: mjpeg
    name: 3D Printer
    still_image_url: http://192.168.1.121:9999/webcam/?action=snapshot
    mjpeg_url: http://192.168.1.121:9999/webcam/?action=stream
