- platform: rest
  resource: http://192.168.1.154:2080/api/192.168.1.126/status
  name: smarter_coffee_status
  scan_interval: 20
  value_template: '{{ value_json.status.ready }}'

rest_command:
  make_coffee:
    url: 'http://192.168.1.154:2080/api/192.168.1.126/brew/default'