- platform: rest
  resource: http://192.168.1.154:2080/api/<smarter-coffee ip>/status
  name: smarter_coffee_status
  scan_interval: 20
  value_template: '{{ value_json.status.ready }}'

rest_command:
  make_coffee:
    url: 'http://192.168.1.154:2080/api/<coffee ip>/brew/default'